name: ${pluginName}
#description: Plugin description for ${pluginName}
version: ${project.parent.version}
api-version: '1.13'

main: ${project.parent.groupId}.${project.parent.artifactId}.BetterChairsPlugin

author: Sprax2013
authors: [ Sprax2013, BlackScarx ]
website: https://github.com/SpraxDev/BetterChairs

commands:
  ${pluginName}:
    description: 'Toggle, Reload or Reset BetterChairs'
  toggleChairs:
    description: 'Allows individual players to disabled chairs for them'
    aliases:
      - bct
    permission: ${pluginName}.cmd.toggle

permissions:
  ${pluginName}.use:
    description: Allows players to sit on stairs
    default: true
  ${pluginName}.regeneration:
    description: Grants regeneration to a player when sitting
  ${pluginName}.updater:
    descritpion: Notifies players about updates when joining the server
  ${pluginName}.cmd.toggle:
    description: Allows individual players to disabled chairs for them
    default: true
  ${pluginName}.cmd.reset:
    description: Allows players to eject all players from their chairs
  ${pluginName}.cmd.reload:
    description: Allows players to reload the plugin's configuration files